services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=database'
      - 'POSTGRES_USER=database'
    ports:
      - '5432:5432'
